/**
 * admin/products.js — Admin Product Management JS
 * Modal tambah/edit produk, preview gambar, konfirmasi hapus.
 */

// ── Delete Confirmation ──────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
    // Tombol hapus produk — konfirmasi sebelum submit form
    document.querySelectorAll('[data-confirm-delete]').forEach(btn => {
        btn.addEventListener('click', (e) => {
            e.preventDefault();
            const productName = btn.dataset.productName ?? 'produk ini';
            if (confirm(`Hapus "${productName}"? Tindakan ini tidak bisa dibatalkan.`)) {
                btn.closest('form').submit();
            }
        });
    });

    // Preview gambar sebelum upload
    const imageInput = document.getElementById('product-image-input');
    const imagePreview = document.getElementById('product-image-preview');

    if (imageInput && imagePreview) {
        imageInput.addEventListener('change', () => {
            const file = imageInput.files[0];
            if (!file) return;

            const reader = new FileReader();
            reader.onload = (e) => {
                imagePreview.src = e.target.result;
                imagePreview.classList.remove('hidden');
            };
            reader.readAsDataURL(file);
        });
    }

    // Auto-generate slug dari nama produk
    const nameInput = document.getElementById('product-name');
    const skuInput  = document.getElementById('product-sku');

    if (nameInput && skuInput) {
        nameInput.addEventListener('input', () => {
            // Hanya auto-generate jika field SKU masih kosong
            if (skuInput.dataset.autoGenerated !== 'false') {
                skuInput.dataset.autoGenerated = 'true';
            }
        });
    }
});
